name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build MusicService
      run: mvn -B package --file MusicService/pom.xml
    - name: Test MusicService
      run: mvn test --file MusicService/pom.xml
    - name: Build MockLibrary
      run: mvn -B package --file MockLibrary/pom.xml
    - name: Test MockLibrary
      run: mvn test --file MockLibrary/pom.xml
